NER_CONFIGS = {"pipeline": {"task": "ner", "model_type": "bert", "do_train": True, "do_predict": True, "evaluate_during_training": True}, "model": {"config_name": None, "model_name_or_path": "fst/pretrained_model", "prediction_model_dir": None},"tokenizer": {"tokenizer_name": None}, "train": {"output_dir": "fst/output_dir", "cache_dir": None, "result_dir": None, "per_gpu_train_batch_size": 8, "per_gpu_eval_batch_size": 8, "gradient_accumulation_steps": 1, "learning_rate": "5e-5", "weight_decay": 5e-05, "adam_epsilon": 1e-08, "max_grad_norm": 1.0, "num_train_epochs": 3, "max_steps": -1, "warmup_steps": 0, "logging_steps": 500, "save_steps": 500, "eval_all_checkpoints": True, "no_cuda": True, "overwrite_output_dir": False, "overwrite_cache": False, "fp16": False, "fp16_opt_level": "O1", "local_rank": -1}, "data": {"max_seq_length": 128, "do_lower_case": True, "data_dir": "fst/data", "label_file": "fst/data/labels.txt", "delimiter": "\t"}, "others": {"seed": 0, "tensorboard_dir": "runs/ner", "result_dir": "fst/result_dir"}}


TEXTCLASSIFICATION_CONFIG = {"pipeline": {"task": "text-classification","model_type": "bert", "do_train": True, "do_predict": True, "evaluate_during_training": True}, "model": {"config_name": None, "model_name_or_path": "fst/pretrained_model", "prediction_model_dir": None},"tokenizer": {"tokenizer_name": None}, "train": {"output_dir": "fst/output_dir", "cache_dir": None, "result_dir": None, "per_gpu_train_batch_size": 8, "per_gpu_eval_batch_size": 8, "gradient_accumulation_steps": 1, "learning_rate": "5e-5", "weight_decay": 5e-05, "adam_epsilon": 1e-08, "max_grad_norm": 1.0, "num_train_epochs": 3, "max_steps": -1, "warmup_steps": 0, "logging_steps": 500, "save_steps": 500, "eval_all_checkpoints": True, "no_cuda": True, "overwrite_output_dir": False, "overwrite_cache": False, "fp16": False, "fp16_opt_level": "O1", "local_rank": -1}, "data": {"max_seq_length": 128, "do_lower_case": True, "data_dir": "fst/data", "label_file": "fst/data/labels.txt", "delimiter": "\t", "column_label": 0, "column_text": 1, "skip_first_row": True}, "others": {"seed": 0, "tensorboard_dir": "runs/ner", "result_dir": "fst/result_dir"}}


TASK_CONFIGS = {
    "ner": NER_CONFIGS,
    "text-classification": TEXTCLASSIFICATION_CONFIG
}